version: '3'

services:
  db:
    restart: always
    image: postgres:16-alpine
    environment:
          - POSTGRES_DB=postgres
          - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
